/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package project_test

import (
	"os"
	"path/filepath"
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"sigs.k8s.io/kubebuilder/v4/pkg/mcp/project"
)

func TestProject(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "project suite")
}

const sampleProjectFile = `# Code generated by tool. DO NOT EDIT.
version: "3"
domain: example.com
repo: github.com/example/myoperator
projectName: myoperator
cliVersion: 4.5.0
layout:
- go.kubebuilder.io/v4
- kustomize.common.kubebuilder.io/v2
resources:
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  group: apps
  kind: Foo
  plural: foos
  version: v1alpha1
- controller: true
  group: apps
  kind: Bar
  plural: bars
  version: v1beta1
  webhooks:
    defaulting: true
    validation: true
    webhookVersion: v1
`

var _ = Describe("LoadContext", func() {
	var tmpDir string

	BeforeEach(func() {
		var err error
		tmpDir, err = os.MkdirTemp("", "mcp-project-test-*")
		Expect(err).NotTo(HaveOccurred())
	})

	AfterEach(func() {
		Expect(os.RemoveAll(tmpDir)).To(Succeed())
	})

	It("returns ErrNotProject when PROJECT file is missing", func() {
		_, err := project.LoadContext(tmpDir)
		Expect(err).To(HaveOccurred())
		var notProject project.ErrNotProject
		Expect(err).To(BeAssignableToTypeOf(notProject))
		Expect(err.Error()).To(ContainSubstring("PROJECT"))
	})

	It("loads a valid project and returns a populated Context", func() {
		err := os.WriteFile(filepath.Join(tmpDir, "PROJECT"), []byte(sampleProjectFile), 0o600)
		Expect(err).NotTo(HaveOccurred())

		ctx, err := project.LoadContext(tmpDir)
		Expect(err).NotTo(HaveOccurred())
		Expect(ctx).NotTo(BeNil())

		Expect(ctx.RootDir).To(Equal(tmpDir))
		Expect(ctx.ProjectVersion).To(Equal("3"))
		Expect(ctx.Domain).To(Equal("example.com"))
		Expect(ctx.Repository).To(Equal("github.com/example/myoperator"))
		Expect(ctx.ProjectName).To(Equal("myoperator"))
		Expect(ctx.CliVersion).To(Equal("4.5.0"))
		Expect(ctx.PluginChain).To(ContainElements(
			"go.kubebuilder.io/v4",
			"kustomize.common.kubebuilder.io/v2",
		))
		Expect(ctx.MultiGroup).To(BeFalse())

		Expect(ctx.APIs).To(HaveLen(2))

		foo := ctx.APIs[0]
		Expect(foo.Group).To(Equal("apps"))
		Expect(foo.Kind).To(Equal("Foo"))
		Expect(foo.Version).To(Equal("v1alpha1"))
		Expect(foo.Controller).To(BeTrue())
		Expect(foo.HasAPI).To(BeTrue())
		Expect(foo.Namespaced).To(BeTrue())
		Expect(foo.Webhooks).To(BeNil())

		bar := ctx.APIs[1]
		Expect(bar.Group).To(Equal("apps"))
		Expect(bar.Kind).To(Equal("Bar"))
		Expect(bar.Webhooks).NotTo(BeNil())
		Expect(bar.Webhooks.Defaulting).To(BeTrue())
		Expect(bar.Webhooks.Validation).To(BeTrue())
		Expect(bar.Webhooks.Conversion).To(BeFalse())
	})

	It("uses the working directory when dir is empty", func() {
		orig, err := os.Getwd()
		Expect(err).NotTo(HaveOccurred())
		DeferCleanup(func() { Expect(os.Chdir(orig)).To(Succeed()) })

		Expect(os.Chdir(tmpDir)).To(Succeed())
		_, err = project.LoadContext("")
		Expect(err).To(HaveOccurred())
		var notProject project.ErrNotProject
		Expect(err).To(BeAssignableToTypeOf(notProject))
	})
})
